version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.5
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
         name: Run tests
         command: npm run test
  surge:
     docker:
       - image: circleci/node:8.5
     working_directory: ~/repo
     steps:
       - checkout
       - restore_cache:
           keys:
           - v1-dependencies-{{ checksum "package.json" }}
           - v1-dependencies-
       - run: npm install
       - run: npm run build
       - run: npm run deploy-surge -- -d seek-asia-style-guide--$CIRCLE_SHA1.surge.sh
  deploy:
    docker:
      - image: circleci/node:8.5
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: npm install
      - run: git config --global user.name "Circle-CI";
      - run: git config --global user.email "srp-dev@seekasia.com";
      - run: npm run build-gh-pages
      - run: npm run deploy-gh-pages
      - run: npm run semantic-release
workflows:
  version: 2
  status-check:
    jobs:
      - build:
          filters:
            branches:
              ignore: master
      - surge:
          requires:
            - build
          filters:
            branches:
              ignore: master
  deploy-ghpages:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
